name: Merge when ready
on:
  workflow_run:
    workflows: [ "Check CLA" ]
    types:
      - completed
permissions:
  pull-requests: read
  contents: write

jobs:
  enable-auto-merge:
    runs-on: ubuntu-latest
    steps:
      - uses: alexwilson/enable-github-automerge-action@main
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
          merge-method: "SQUASH"
