name: Merge when ready
on:
  pull_request:
    types:
      - opened
      - reopened

jobs:
  enable-auto-merge:
    runs-on: ubuntu-latest
    steps:
      - uses: alexwilson/enable-github-automerge-action@main
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
          merge-method: "SQUASH"
